version: "3.8"

services:
  app:
    container_name: belajar-expressjs
    image: belajar-expressjs
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "127.0.0.1:3000:80"
